name: 'Wush'
description: 'SSH into GitHub Actions'
runs:
  using: 'composite'
  steps:
    - name: Install and run wush
      shell: bash
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        TMP_DIR=$(mktemp -d)
        cd "$TMP_DIR"

        SCRIPT_PATH="${{ github.action_path }}/download-wush.sh"
        chmod +x "$SCRIPT_PATH"
        
        ARG_OS="${{ runner.os }}" \
        ARG_ARCH="${{ runner.arch }}" \
        "$SCRIPT_PATH"
        
        ./wush serve
