name: 'Wush'
description: 'SSH into GitHub Actions'
runs:
  using: 'composite'
  steps:
    - name: Install wush
      shell: bash
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        INSTALL_DIR="$RUNNER_TEMP/wush"
        rm -rf "$INSTALL_DIR"
        mkdir -p "$INSTALL_DIR"
        cd "$INSTALL_DIR"

        SCRIPT_PATH="${{ github.action_path }}/download-wush.sh"
        chmod +x "$SCRIPT_PATH"
        
        ARG_OS="${{ runner.os }}" \
        ARG_ARCH="${{ runner.arch }}" \
        "$SCRIPT_PATH"

    - name: Run wush
      shell: bash
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset

        cd "$RUNNER_TEMP/wush"
        ./wush serve
